### ISSUE TITLE
Single Image Erasure

### ISSUE THREAD

**Issue by Ferry-Li** [rohitgandikota/erasing#30]
Thanks for your amazing work!
I have a question for Appendix C, where you just removed a single image from the model.
I wonder how you apply the guidance here. Did you use exactly the image or just a text prompt "Starry Night"?
If you use the image, can you introduce how you add the image in the guidance process?
If you just use the text prompt "Starry Night", can the diffusion model tell the difference between a common starry night and Van Gogh's work "Starry Night"?

**Comment by rohitgandikota** [comment]
Good question! The way we do it is - instead of using the diffusion model to generate images, we use the original image to generate the noised version of the image in the training (basically add noise to the original image). Then we use the prompt "Starry Night" 

Since the diffusion model is shown the prior image of Van Gogh Starry Night - that seems to do the trick for specifically erasing starry night compared to the regular starry night
